<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('1337 '. $this->translate('Templetariano'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/saegeSpa.js')
        ; ?>

    </head>
    <body>
        <script>
        
        </script>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a onmousedown='return false;' onselectstart="return false;" class="navbar-brand" href="<?php echo $this->url('home') ?>" onclick="loadAjax(event,'<?php echo $this->serverUrl().$this->url('home') ?>',true)" ><img style="width:20px;" src="<?php echo $this->basePath('img/saege.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Saegfreds SPA mit PHP') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" onmousedown='return false;' onselectstart="return false;">
                        <li id="home" <?php echo (($this->url()=="/")?"class='active'":"") ?> ><a style="width:100px;text-align:center;" href="<?php echo $this->url('home') ?>" onclick="loadAjax(event,'<?php echo $this->serverUrl().$this->url('home') ?>')" ><?php echo $this->translate('Home') ?></a></li>
                        <li id="news" <?php echo (($this->url()=="/news")?"class='active'":"") ?> ><a style="width:100px;text-align:center;" href="<?php echo $this->url('news') ?>" onclick="loadAjax(event,'<?php echo $this->serverUrl().$this->url('news') ?>')" ><?php echo $this->translate('News') ?></a></li>
                        <li id="about" <?php echo (($this->url()=="/about")?"class='active'":"") ?>><a style="width:100px;text-align:center;" href="<?php echo $this->url('about') ?>" onclick="loadAjax(event,'<?php echo $this->serverUrl().$this->url('about') ?>')" ><?php echo $this->translate('About') ?></a></li>
                        <li id="kontakt" <?php echo (($this->url()=="/kontakt")?"class='active'":"") ?>><a style="width:100px;text-align:center;" href="<?php echo $this->url('kontakt') ?>" onclick="loadAjax(event,'<?php echo $this->serverUrl().$this->url('kontakt') ?>')" ><?php echo $this->translate('Kontakt') ?></a></li>
                        <li id="impressum" <?php echo (($this->url()=="/impressum")?"class='active'":"") ?>><a style="width:100px;text-align:center;" href="<?php echo $this->url('impressum') ?>" onclick="loadAjax(event,'<?php echo $this->serverUrl().$this->url('impressum') ?>')" ><?php echo $this->translate('Impressum') ?></a></li>                            
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div id="main">
                <!--content-->
                    <?php echo $this->content; ?>
                <!--/content-->
            </div>
            <hr>
            <footer>
                <p><?php echo date('D M Y') ?> von Saegi powered by Zend Framework</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
